### ISSUE TITLE
Exception on song upload

### ISSUE THREAD

**Issue by maldouk** [jaymoulin/youtube-music-uploader#4]
**Description**
While trying to upload with the following command:
youtube-music-upload -d "D:\Music"

I'm getting this Exception in logs:
youtube_music_uploader.uploader_daemon - INFO - Uploading D:\Musique\song.mp3
youtube_music_uploader.uploader_daemon - INFO - Exception: Not uploaded D:\Musique\song.mp3: 'x-goog-upload-url'
and this error message in console:

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Python310\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "C:\Python310\lib\site-packages\watchdog\observers\api.py", line 199, in run
    self.dispatch_events(self.event_queue, self.timeout)
  File "C:\Python310\lib\site-packages\watchdog\observers\api.py", line 372, in dispatch_events
    handler.dispatch(event)
  File "C:\Python310\lib\site-packages\watchdog\events.py", line 272, in dispatch
    {
  File "C:\Python310\lib\site-packages\youtube_music_uploader\uploader_daemon.py", line 44, in on_created
    upload_file(
  File "C:\Python310\lib\site-packages\youtube_music_uploader\uploader_daemon.py", line 121, in upload_file
    raise e
  File "C:\Python310\lib\site-packages\youtube_music_uploader\uploader_daemon.py", line 89, in upload_file
    status = api.upload_song(file_path)
  File "C:\Python310\lib\site-packages\ytmusicapi\mixins\uploads.py", line 217, in upload_song
    upload_url = response.headers['X-Goog-Upload-URL']
  File "C:\Python310\lib\site-packages\requests\structures.py", line 54, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'x-goog-upload-url'
```

Logging went without a hitch, so I believe I did things right on this point.
Waiting on your aswer! Thank you for the work.

**Comment by jaymoulin** [comment]
Maintaining an application (answering questions, fixing bugs, adding new features...) is a hard and time consuming process. If you find this product useful and all the effort I put crafting this, I strongly encourage you to donation to help me being able to continue maintaining this and creating other great things on those platforms [![PayPal donation](https://github.com/jaymoulin/jaymoulin.github.io/raw/master/ppl.png "PayPal donation")](https://www.paypal.me/jaymoulin) [![Buy me a coffee](https://www.buymeacoffee.com/assets/img/custom_images/orange_img.png "Buy me a coffee")](https://www.buymeacoffee.com/3Yu8ajd7W) [![Become a Patron](https://badgen.net/badge/become/a%20patron/F96854 "Become a Patron")](https://patreon.com/jaymoulin).

Your issue is missing most of required information, but it seems you may have missed the auth instructions : https://github.com/jaymoulin/youtube-music-uploader#installation / https://github.com/jaymoulin/youtube-music-uploader/tree/master/docker#configuration
